# -*- coding:utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from time import sleep
from public import *

def create_columnA(name, password):

    login(name, password)
    sleep(1.5)
    dr.find_element_by_xpath('//*[@id="nav"]/ul/li[3]').click()
    dr.switch_to_frame('menu')
    dr.find_element_by_xpath('//*[@id="tree_1_a"]').click()
    dr.switch_to.parent_frame()
    dr.switch_to_frame('page')
    dr.find_element_by_xpath('//*[@id="grid_toolbar"]/div[1]/a[1]').click()
    sleep(0.2)
    dr.switch_to.parent_frame()
    dr.switch_to_frame('page')
    dr.find_element_by_xpath('//*[@id="vc_cataname"]').send_keys('栏目A')
    dr.find_element_by_xpath('//*[@id="select_i_style"]').click()
    dr.find_element_by_xpath('//*[@id="select_i_style_menu"]/div/ul/li[3]').click()
    dr.find_element_by_xpath('//*[@id="page-toolbar"]/div/table/tbody/tr/td[1]/input').click()
    sleep(5)

def set_attributes():
    dr.switch_to_default_content()
    dr.switch_to_frame('page')
    dr.find_element_by_xpath('//*[@id="datagrid-row-r1-2-1"]/td[5]/div/div').click()
    sleep(1.5)
    dr.switch_to.parent_frame()
    dr.switch_to_frame('dialog_frame')
    dr.find_element_by_xpath('//*[@id="vc_name"]').send_keys('长文本字段')
    dr.find_element_by_xpath('//*[@id="select_i_fieldtype"]').click()
    sleep(0.5)
    dr.find_element_by_xpath('//*[@id="select_i_fieldtype_menu"]/div/ul/li[12]').click()
    dr.find_element_by_xpath('//*[@id="oprform"]/div[2]/input[1]').click()
    sleep(1.5)
    dr.find_element_by_xpath('//*[@id="vc_name"]').send_keys('图片字段')
    dr.find_element_by_xpath('//*[@id="select_i_fieldtype"]').click()
    sleep(0.5)
    dr.find_element_by_xpath('//*[@id="select_i_fieldtype_menu"]/div/ul/li[6]').click()
    dr.find_element_by_xpath('//*[@id="oprform"]/div[2]/input[1]').click()
    sleep(1.5)
    dr.find_element_by_xpath('//*[@id="vc_name"]').send_keys('附件字段')
    dr.find_element_by_xpath('//*[@id="select_i_fieldtype"]').click()
    sleep(0.5)
    dr.find_element_by_xpath('//*[@id="select_i_fieldtype_menu"]/div/ul/li[8]').click()
    dr.find_element_by_xpath('//*[@id="oprform"]/div[2]/input[1]').click()
    sleep(1.5)
    dr.find_element_by_xpath('//*[@id="vc_name"]').send_keys('短文本字段')
    dr.find_element_by_xpath('//*[@id="select_i_fieldtype"]').click()
    sleep(0.5)
    dr.find_element_by_xpath('//*[@id="select_i_fieldtype_menu"]/div/ul/li[11]').click()
    dr.find_element_by_xpath('//*[@id="oprform"]/div[2]/input[1]').click()
    sleep(1.5)
    dr.find_element_by_xpath('//*[@id="vc_name"]').send_keys('日期字段')
    dr.find_element_by_xpath('//*[@id="select_i_fieldtype"]').click()
    sleep(0.5)
    dr.find_element_by_xpath('//*[@id="select_i_fieldtype_menu"]/div/ul/li[4]').click()
    dr.find_element_by_xpath('//*[@id="oprform"]/div[2]/input[1]').click()
    sleep(1.5)
    dr.find_element_by_xpath('//*[@id="oprform"]/div[2]/input[4]').click()

def create_columnB():
    dr.switch_to_default_content()
    dr.switch_to_frame('page')
    dr.find_element_by_xpath('//*[@id="grid_toolbar"]/div[1]/a[1]').click()
    sleep(0.2)
    dr.switch_to.parent_frame()
    dr.switch_to_frame('page')
    dr.find_element_by_xpath('//*[@id="vc_cataname"]').send_keys('栏目B')
    dr.find_element_by_xpath('//*[@id="select_i_style"]').click()
    dr.find_element_by_xpath('//*[@id="select_i_style_menu"]/div/ul/li[3]').click()
    dr.find_element_by_xpath('//*[@id="custInherit"]').click()
    sleep(0.5)
    dr.switch_to.parent_frame()
    dr.switch_to_frame('dialog_frame')
    dr.find_element_by_xpath('//*[@id="tree_2_a"]').click()
    dr.find_element_by_xpath('//*[@id="inheritChoose"]').click()
    dr.switch_to.parent_frame()
    dr.switch_to_frame('page')
    dr.find_element_by_xpath('//*[@id="page-toolbar"]/div/table/tbody/tr/td[1]/input').click()
    sleep(5)

if __name__ == '__main__':
    create_columnA('test', 'hanweb1')
    set_attributes()
    create_columnB()